### ISSUE TITLE
SSR

### ISSUE THREAD

**Issue by krasevych** [kaorun343/vue-property-decorator#16]
I use Nuxt and there is SSR, I try to use `property-decorator` with SSR but got a error:

My component:
```javascript
import Vue from 'vue';
import { Component, Prop } from 'src/plugins/classComponent';

@Component()
class MainHeader extends Vue {
  @Prop({ type: String })
  title;
}

export default MainHeader;
```

error:
```javascript
TypeError: Cannot redefine property: title
    at Object.defineProperty (<anonymous>)
    at defineProperty (~/core-js/library/fn/object/define-property.js:4:0)
    at _initDefineProp (0.server-bundle.js:316:32)
    at new MainHeader (0.server-bundle.js:371:207)
    at collectDataFromConstructor (D:\Projects\Vue\smart-landing\node_modules\vue-class-component\dist\vue-class-component.common.js:48:16)
    at VueComponent.data (D:\Projects\Vue\smart-landing\node_modules\vue-class-component\dist\vue-class-component.common.js:104:20)
    at getData (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:2751:17)
    at initData (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:2720:7)
    at initState (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:2661:5)
    at VueComponent.Vue._init (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:3752:5)
```

**Comment by kaorun343** [comment]
@krasevych 

Hi.
This library has a problem with Babel, so this library doesn't support it.

https://github.com/vuejs/vue-class-component/issues/50

**Comment by krasevych** [comment]
do you plan to support babel?

**Comment by krasevych** [comment]
@kaorun343 do you plan to support babel?

**Comment by kaorun343** [comment]
No, I cannot support it.
As described at the last comment of that issue, `title` in your example becomes `undefined` when using Babel.
