### ISSUE TITLE
e.stopPropagation is not a function

### ISSUE THREAD

**Issue by alamhubb** [kaorun343/vue-property-decorator#441]
vue2 can work
```
  @Emit()
  click() {
    return ''
  }
```
vue3 not work

vue3 can work
```
  @Emit()
  click() {
    return
  }
```

error info
```
vue.runtime.esm.js:10760 Uncaught TypeError: e.stopPropagation is not a function
    at stop (vue.runtime.esm.js:10760:18)
    at vue.runtime.esm.js:10785:26
    at callWithErrorHandling (vue.runtime.esm.js:1336:22)
    at callWithAsyncErrorHandling (vue.runtime.esm.js:1345:21)
    at emit$1 (vue.runtime.esm.js:1908:9)
    at emit (vue-property-decorator.js?v=68f005a1:445:16)
    at Proxy.emitter (vue-property-decorator.js?v=68f005a1:452:9)
    at callWithErrorHandling (vue.runtime.esm.js:1336:22)
    at callWithAsyncErrorHandling (vue.runtime.esm.js:1345:21)
    at HTMLElement.invoker (vue.runtime.esm.js:9628:9)
```

beacuse // if (returnValue === undefined) {  in the emit.js    ,  The return value need is undefined
```
export function Emit(event) {
    return createDecorator((componentOptions, propertyKey) => {
        const emitName = event || hyphenate(propertyKey);
        componentOptions.emits || (componentOptions.emits = []);
        componentOptions.emits.push(emitName);
        const original = componentOptions.methods[propertyKey];
        componentOptions.methods[propertyKey] = function emitter(...args) {
            const emit = (returnValue) => {
                if (returnValue === undefined) {
                    if (args.length === 0) {
                        this.$emit(emitName);
                    }
                    else if (args.length === 1) {
                        this.$emit(emitName, args[0]);
                    }
                    else {
                        this.$emit(emitName, ...args);
                    }
                }
                else {
                    args.unshift(returnValue);
                    this.$emit(emitName, ...args);
                }
            };
            const returnValue = original.apply(this, args);
            if (isPromise(returnValue)) {
                returnValue.then(emit);
            }
            else {
                console.log(returnValue)
                emit(returnValue);
            }
            return returnValue;
        };
    });
}
```

**Comment by alamhubb** [comment]
vue3 can work
``` 
 @Emit()
  click() {
    return
  }
```
